#!/usr/bin/env bash

set -euo pipefail

cat > /etc/os-image-metadata <<EOF
IMAGE_NAME="${VM_NAME}",
BUILD_VERSION="${BUILD_VERSION}"
BUILD_DATE="${BUILD_TIMESTAMP}",
BASE_IMAGE="${BASE_IMAGE_URL}",
PACKER_GIT_REMOTE="${GIT_REMOTE_URL}"
PACKER_GIT_COMMIT="${GIT_COMMIT_REF}"
EOF
