#!/usr/bin/env bash

set -euo pipefail

qemu-img info "${IMAGE_PATH}"
qemu-img check "${IMAGE_PATH}"

( cd "${OUTPUT_DIRECTORY}" && sha512sum "${VM_NAME}" ) > "${CHECKSUM_PATH}"

SHA512_CHECKSUM=$(awk '{print $1}' "${CHECKSUM_PATH}")
METADATA_PATH="${OUTPUT_DIRECTORY}/${IMAGE_METADATA_NAME}"

cat > "${METADATA_PATH}" <<EOF
{
  "IMAGE_NAME":         "${VM_NAME}",
  "SHA512_CHECKSUM":    "${SHA512_CHECKSUM}",
  "BUILD_VERSION":      "${BUILD_VERSION}",
  "BUILD_DATE":         "${BUILD_TIMESTAMP}",
  "BASE_IMAGE":         "${BASE_IMAGE_URL}",
  "PACKER_GIT_REMOTE":  "${GIT_REMOTE_URL}"
  "PACKER_GIT_COMMIT":  "${GIT_COMMIT_REF}"
}
EOF

"${MINIO_CLIENT}" mb --ignore-existing "${MINIO_PUBLISH_PATH}"
"${MINIO_CLIENT}" anonymous -r set download "${MINIO_PUBLISH_PATH}"

"${MINIO_CLIENT}" cp "${IMAGE_PATH}" "${MINIO_PUBLISH_PATH}"/"${BUILD_VERSION}"/
"${MINIO_CLIENT}" cp "${CHECKSUM_PATH}" "${MINIO_PUBLISH_PATH}"/"${BUILD_VERSION}"/
"${MINIO_CLIENT}" cp "${METADATA_PATH}" "${MINIO_PUBLISH_PATH}"/"${BUILD_VERSION}"/

ALL_EXISTING_METADATA=$("${MINIO_CLIENT}" cat "${MINIO_PUBLISH_PATH}/${ALL_METADATA_NAME}" 2>/dev/null || printf '%s\n' '[]')
ALL_EXISTING_METADATA=$(jq --slurpfile o "${METADATA_PATH}" '. + [$o[0]]' <<<"${ALL_EXISTING_METADATA}")

printf '%s\n' "${ALL_EXISTING_METADATA}" | "${MINIO_CLIENT}" pipe "${MINIO_PUBLISH_PATH}/${ALL_METADATA_NAME}"
