#!/usr/bin/env bash

set -euxo pipefail
cp "${IMAGE_PATH}" "${LATEST_IMAGE_PATH}"

( cd "${OUTPUT_DIRECTORY}" && sha512sum "${VM_NAME}" ) > "${CHECKSUM_PATH}"
( cd "${OUTPUT_DIRECTORY}" && sha512sum "${LATEST_VM_NAME}" ) > "${LATEST_CHECKSUM_PATH}"

qemu-img info "${IMAGE_PATH}"
qemu-img check "${IMAGE_PATH}"

SHA512_CHECKSUM=$(awk '{print $1}' "${CHECKSUM_PATH}")

cat > "${METADATA_PATH}" <<EOF
{
  "IMAGE_NAME":         "${VM_NAME}",
  "SHA512_CHECKSUM":    "${SHA512_CHECKSUM}",
  "BUILD_DATE":         "${BUILD_TIMESTAMP}",
  "BASE_IMAGE":         "${BASE_IMAGE_URL}",
  "PACKER_GIT_COMMIT":  "${GIT_COMMIT_REF}"
}
EOF

"${MINIO_CLIENT}" mb --ignore-existing "${MINIO_PUBLISH_PATH}"
"${MINIO_CLIENT}" anonymous -r set download "${MINIO_PUBLISH_PATH}"

"${MINIO_CLIENT}" cp "${IMAGE_PATH}" "${MINIO_PUBLISH_PATH}"/"${BUILD_VERSION}"/
"${MINIO_CLIENT}" cp "${CHECKSUM_PATH}" "${MINIO_PUBLISH_PATH}"/"${BUILD_VERSION}"/
"${MINIO_CLIENT}" cp "${METADATA_PATH}" "${MINIO_PUBLISH_PATH}"/"${BUILD_VERSION}"/

"${MINIO_CLIENT}" cp "${LATEST_IMAGE_PATH}" "${LATEST_MINIO_PUBLISH_PATH}"/
"${MINIO_CLIENT}" cp "${LATEST_CHECKSUM_PATH}" "${LATEST_MINIO_PUBLISH_PATH}"/
