- name: pre-requisite packages for secret management
  hosts: all
  become: true
  roles:
    - role: sops
      sops_version: "3.13.3"

- name: basic configuration for all debian systems
  hosts: all
  become: true
  roles:
    - role: system
      system_allow_release_info_change: false
      system_timezone: "Europe/Helsinki"
      system_install_packages:
        - age
        - nfs-common
        - python3-debian # required by ansible.builtin.deb822_repository module
        - qemu-guest-agent
      system_remove_packages:
        - apt-listchanges
        - bash-completion
        - bind9-host
        - curl
        - groff-base
        - man-db
        - manpages
        - nano
        - pciutils
        - reportbug
        - screen
        - socat
        - ssh-import-id
        - tcpdump
        - traceroute
        - vim
        - vim-tiny
        - wget

    - role: security
      security_ssh_service_name: "sshd"

    - role: ssh_keysign
      ssh_keysign_version: "0.0.10"
