- name: set computed facts
  hosts: all
  tasks:
    - name: set normalized architecture fact
      ansible.builtin.set_fact:
        normalized_arch: >-
          {{
          'amd64' if ansible_facts['architecture'] == 'x86_64' else
          'arm64' if ansible_facts['architecture'] == 'aarch64' else
          ansible_facts['architecture']
          }}

- name: configure media server
  hosts: all
  become: true
  vars:
    systemd_app_apps_dir: "{{ playbook_dir }}/apps"
  roles:
    - role: binarycodes.homelab.systemd_app
      systemd_app_kind: source
      systemd_app_name: immich

    - role: binarycodes.homelab.systemd_app
      systemd_app_kind: source
      systemd_app_name: caddy-lab
