name: check for packer image updates

on:
  schedule:
      #      ┌───────────── minute (0 - 59)
      #      │ ┌───────────── hour (0 - 23)
      #      │ │   ┌───────────── day of the month (1 - 31)
      #      │ │   │ ┌───────────── month (1 - 12 or JAN-DEC)
      #      │ │   │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
      #      │ │   │ │ │
    - cron: "0 0/1 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  debian-base-update:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6.0.2

      - name: update base image source
        run: |
          ./.github/workflows/scripts/check-debian-base-image-update.sh
          make debian-container-validate
          make debian-kubernetes-validate

      - name: create pr
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          sign-commits: true
          commit-message: "chore: bump debian base image"
          title: "chore: bump debian base image"
          body: |
            automated update of debian base image.
          branch: chore/debian-base-image-bump

  debian-container-update:
    runs-on: self-hosted
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6.0.2

      - name: update container image source
        run: |
          ./.github/workflows/scripts/check-debian-container-image-update.sh
          make debian-edge-validate

      - name: create pr
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          sign-commits: true
          commit-message: "chore: bump debian container image"
          title: "chore: bump debian container image"
          body: |
            automated update of debian container image.
          branch: chore/debian-container-image-bump
