name: run validations

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate:
    runs-on: [self-hosted]

    steps:
      - name: checkout repository
        uses: actions/checkout@v6.0.2

      - name: validate
        run: |
          make debian-base-validate
          make debian-container-validate
          make debian-kubernetes-validate
          shellcheck ./.github/workflows/scripts/*
